name: Build and publish Vue pages
on:
  push:
    branches:
    - master
jobs:
  build_publish:
    runs-on: ubuntu-latest
    name: Build and publish Vue pages
    steps:
    - uses: actions/checkout@v2
    - run: npm install -g synp
    - run: yarn
    - run: synp --source-file $GITHUB_WORKSPACE/yarn.lock
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'mamounometre'
        reponame: 'mamounometre'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged